/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_helper_Divide */

#ifndef _Included_com_example_demo_helper_Divide
#define _Included_com_example_demo_helper_Divide
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_helper_Divide
 * Method:    ndiv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_demo_helper_Divide_ndiv
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
